.PHONY: format lint clean

# Formatage du code
format:
	cd vendezvotresaucisse &&
	npx prettier --write .

lint:
	cd vendezvotresaucisse &&
	npx eslint . --ext .js,.jsx,.ts,.tsx

clean:
	cd vendezvotresaucisse &&
	rm -rf dist node_modules
